apiVersion: v1
kind: Service
metadata:
  name: itiic-podinfo
spec:
  type: ClusterIP
  selector:
    app: itiic-podinfo
  ports:
    - name: http
      port: 19898
      protocol: TCP
      targetPort: http
    - port: 19999
      targetPort: grpc
      protocol: TCP
      name: grpc
